# Header
menu:
  Home: /
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false

# Sidebar
sidebar: right
widgets:
- ad
- author
- archive
- category
- search

# widget behavior
archive_type: 'yearly'
show_count: true
